#!/usr/bin/env python

from manim import *
from math import factorial

class EulerFormula(Scene):
    def construct(self):
        # Display the series
        formula = MathTex(r"\sum_{k=0}^{\infty} \frac{1}{k!} = e")
        self.play(Create(formula))

        # Create a series of rectangles to visualize the sum
        rectangles = VGroup()
        prev_rect = None
        sum_val = 1
        for k in range(1, 10):
            sum_val += 1 / factorial(k)
            rect = Rectangle(height=0.2, width=0.2 * (1 / factorial(k)), fill_opacity=0.5)
            rect.next_to(formula, DOWN, buff=0.1)
            if prev_rect:
                rect.next_to(prev_rect, RIGHT, buff=0)
            self.play(Create(rect))
            rectangles.add(rect)
            prev_rect = rect

        # Highlight the sum as it approaches e
        highlight_box = SurroundingRectangle(rectangles, buff=0.1, color=YELLOW)
        self.play(Create(highlight_box))
        self.wait(2)

        # Transition to showing e with extra space
        e_value = MathTex("e = 2.71828...").next_to(formula, RIGHT, buff=1)
        self.play(ReplacementTransform(formula, e_value))
        self.wait(3)

