#!/usr/bin/env python

from manim import *

class EulersConstant(Scene):
    def construct(self):
        # Display the series with a specific size
        formula = MathTex(r"\frac{1}{k!}\propto \frac{e^k k^{-k-1/2}}{\sqrt{2 \pi } \left(\sum _{\mathcal{A}=1}^{\infty } \sum _{j=1}^{2 \mathcal{A}} \frac{(-1)^j 2^{-\mathcal{A}-j}
k^{-\mathcal{A}} \text{PermutationCyclesD}(2 (\mathcal{A}+j),j)}{(\mathcal{A}+j)!}+1\right)}\text{/;}(\left| \arg (k)\right| <\pi \land (\left| k\right|
\to \infty )\land \text{PermutationCyclesD}(m,j)=(m-1) ((m-2) \text{PermutationCyclesD}(m-3,j-1)+\text{PermutationCyclesD}(m-1,j))\land \text{PermutationCyclesD}(0,0)=1\land
\text{PermutationCyclesD}(m,1)=(m-1)!\land \text{PermutationCyclesD}(m,j)=0\text{/;}m\leq 3 j-1)", size=0.4)
        self.play(Create(formula), run_time=2.5)
        self.wait(2)
