#!/usr/bin/env python

from manim import *


class EulersConstant(Scene):
    def construct(self):
        # Display the series
        formula = MathTex(r"\frac{\sum_{k=0}^{\infty}\frac{z-1+k}{k!}}{z}")
        self.play(Create(formula))
self.wait(3)
